import { createContext, useContext, useState, type ReactNode } from "react";

type Lang = "it" | "en";

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  it: {
    // Navbar
    "nav.home": "Home",
    "nav.about": "About",
    "nav.contact": "Contatti",
    "nav.products": "Prodotti",
    "nav.cta": "Richiedi Demo",

    // Home — Hero
    "home.hero.title1": "Software che lavora per te.",
    "home.hero.title2": "Non il contrario.",
    "home.hero.desc": "ANTHERA sviluppa SaaS moderni per aziende e team che vogliono automatizzare, governare e crescere — senza dipendere da tool americani.",
    "home.hero.cta1": "Scopri PowerLeave",
    "home.hero.cta2": "Scopri GOVERN.AI",
    "home.hero.badge1": "Made in Italy",
    "home.hero.badge2": "EU AI Act Ready",
    "home.hero.badge3": "GDPR Native",

    // Home — Why ANTHERA
    "home.why.title": "Perché scegliere",
    "home.why.desc": "Costruiamo software con rigore ingegneristico e compliance nativa per il mercato europeo.",
    "home.why.card1.title": "Sovranità Digitale",
    "home.why.card1.desc": "I nostri prodotti nascono in Europa, per aziende europee. Zero dipendenze da infrastrutture US.",
    "home.why.card2.title": "Stack Moderno",
    "home.why.card2.desc": "React, FastAPI, MongoDB. Architetture scalabili costruite per crescere con il tuo business.",
    "home.why.card3.title": "Compliance Nativa",
    "home.why.card3.desc": "GDPR, EU AI Act, DORA, NIS2. La conformità non è un add-on, è nel DNA del prodotto.",
    "home.why.card4.title": "Per Team Reali",
    "home.why.card4.desc": "Interfacce pensate per chi lavora davvero. Non per chi fa demo.",

    // Home — Products
    "home.products.title": "I nostri prodotti",
    "home.products.desc": "Due piattaforme SaaS progettate per risolvere problemi reali delle aziende europee.",
    "home.products.pl.tag": "HR & TEAM MANAGEMENT",
    "home.products.pl.name": "ANTHERA PowerLeave",
    "home.products.pl.desc": "Gestione ferie e permessi per team moderni. Multi-tenant, dashboard analytics, calendario integrato e chiusure aziendali automatiche.",
    "home.products.pl.cta": "Scopri PowerLeave",
    "home.products.gov.tag": "AI GOVERNANCE",
    "home.products.gov.name": "ANTHERA GOVERN.AI",
    "home.products.gov.desc": "Il Sovereign Control Plane per la governance degli agenti AI aziendali. Audit trail, policy engine e compliance EU in un'unica piattaforma.",
    "home.products.gov.cta": "Scopri GOVERN.AI",

    // Home — Stats
    "home.stats.title": "Costruito con",
    "home.stats.title2": "rigore ingegneristico",
    "home.stats.stat1": "Test backend automatici su PowerLeave",
    "home.stats.stat2": "Test API passati su GOVERN.AI",
    "home.stats.stat3": "Standard EU supportati",

    // Home — CTA
    "home.cta.title1": "Pronto a portare i tuoi processi al",
    "home.cta.title2": "livello successivo",
    "home.cta.desc": "Parla con noi. Nessun impegno, nessuna demo inutile.",
    "home.cta.button": "Contattaci",

    // PowerLeave
    "pl.badge": "Workforce Intelligence",
    "pl.hero.title1": "Gestisci le ferie del tuo team",
    "pl.hero.title2": "in modo semplice e veloce.",
    "pl.hero.title3": "",
    "pl.hero.desc": "PowerLeave automatizza la gestione di assenze, ferie e permessi per la tua azienda. Dashboard intuitiva, approvazioni rapide con un click, analytics avanzate e chiusure aziendali con sistema di deroghe.",
    "pl.hero.cta1": "Inizia Gratis",
    "pl.hero.cta2": "Demo Live",
    "pl.hero.demo": "Demo",
    "pl.hero.democreds": "admin@demo.it / demo123",
    "pl.features.title": "Tutto ciò che",
    "pl.features.title2": "ti serve",
    "pl.f1.title": "Dashboard Intelligente",
    "pl.f1.desc": "Panoramica completa delle assenze del team con statistiche in tempo reale.",
    "pl.f2.title": "Approvazioni Rapide",
    "pl.f2.desc": "Approva o rifiuta le richieste con un click. Notifiche istantanee al team.",
    "pl.f3.title": "Calendario Condiviso",
    "pl.f3.desc": "Visualizza ferie e permessi di tutto il team in un calendario unificato.",
    "pl.f4.title": "Analytics Avanzate",
    "pl.f4.desc": "Report dettagliati su utilizzo ferie, trend e distribuzione delle assenze.",
    "pl.f5.title": "Chiusure Aziendali",
    "pl.f5.desc": "Gestisci le chiusure obbligatorie con sistema di deroghe configurabile.",
    "pl.f6.title": "Multi-Tenant",
    "pl.f6.desc": "Ogni azienda ha il proprio spazio isolato e configurabile, con auth JWT + Google.",
    "pl.stack.title": "Stack moderno, PMI-ready",
    "pl.pricing.title": "Prezzi semplici",
    "pl.pricing.desc": "Inizia gratis, scala quando cresci.",
    "pl.pricing.free.name": "Free",
    "pl.pricing.free.desc": "Per piccoli team che iniziano",
    "pl.pricing.free.price": "€0",
    "pl.pricing.free.unit": "/mese / utente",
    "pl.pricing.free.f1": "Fino a 5 dipendenti",
    "pl.pricing.free.f2": "Dashboard base",
    "pl.pricing.free.f3": "Calendario condiviso",
    "pl.pricing.free.cta": "Inizia gratis",
    "pl.pricing.pro.name": "Pro",
    "pl.pricing.pro.desc": "Per PMI in crescita",
    "pl.pricing.pro.price": "€4,99",
    "pl.pricing.pro.unit": "/mese / utente",
    "pl.pricing.pro.f1": "Fino a 50 dipendenti",
    "pl.pricing.pro.f2": "Analytics avanzate",
    "pl.pricing.pro.f3": "Chiusure aziendali",
    "pl.pricing.pro.f4": "Bacheca annunci",
    "pl.pricing.pro.cta": "Inizia ora",
    "pl.pricing.ent.name": "Enterprise",
    "pl.pricing.ent.desc": "Team grandi e multinazionali",
    "pl.pricing.ent.price": "Custom",
    "pl.pricing.ent.unit": "",
    "pl.pricing.ent.f1": "Dipendenti illimitati",
    "pl.pricing.ent.f2": "SSO / SAML",
    "pl.pricing.ent.f3": "API Access",
    "pl.pricing.ent.f4": "Supporto dedicato",
    "pl.pricing.ent.cta": "Contattaci",
    "pl.pricing.popular": "POPOLARE",

    // GOVERN.AI
    "gov.hero.title1": "Governa i tuoi agenti AI.",
    "gov.hero.title2": "Prima che lo faccia qualcun altro.",
    "gov.hero.desc": "Il Sovereign Control Plane per la governance degli agenti AI aziendali. Policy engine, audit trail completo e compliance nativa agli standard EU in un'unica piattaforma.",
    "gov.hero.cta1": "Richiedi Demo",
    "gov.hero.cta2": "Leggi la Documentazione",
    "gov.features.title1": "Il tuo",
    "gov.features.title2": "control plane",
    "gov.features.title3": "per l'AI",
    "gov.f1.title": "Agent Registry",
    "gov.f1.desc": "Cataloga e classifica tutti gli agenti AI aziendali con livello di rischio.",
    "gov.f2.title": "Policy Engine",
    "gov.f2.desc": "Definisci e applica policy granulari: restriction, approval, rate_limit, logging, retention.",
    "gov.f3.title": "Audit Trail Completo",
    "gov.f3.desc": "Log immutabile di tutte le azioni degli agenti. Mai più black box.",
    "gov.f4.title": "Compliance Dashboard",
    "gov.f4.desc": "Monitoraggio in tempo reale della conformità a 6 standard EU.",
    "gov.f5.title": "AI Compliance Assistant",
    "gov.f5.desc": "Chatbot esperto in normative europee. Domande in italiano o inglese.",
    "gov.f6.title": "Bilingue IT/EN",
    "gov.f6.desc": "Interfaccia e assistente nativo in italiano e inglese. Pensato per aziende EU.",
    "gov.standards.title1": "6 standard EU.",
    "gov.standards.title2": "Nativi.",
    "gov.std1.name": "EU AI Act",
    "gov.std1.desc": "Regolamento europeo sull'intelligenza artificiale",
    "gov.std2.name": "GDPR",
    "gov.std2.desc": "Protezione dei dati personali",
    "gov.std3.name": "ISO 27001",
    "gov.std3.desc": "Sicurezza delle informazioni",
    "gov.std4.name": "ISO 42001",
    "gov.std4.desc": "Gestione dell'intelligenza artificiale",
    "gov.std5.name": "DORA",
    "gov.std5.desc": "Resilienza operativa digitale",
    "gov.std6.name": "NIS2",
    "gov.std6.desc": "Sicurezza delle reti e dei sistemi",
    "gov.stack.title": "Stack Tecnico",
    "gov.pricing.title": "Piani e Prezzi",
    "gov.pricing.desc": "Scegli il piano adatto alla tua organizzazione.",
    "gov.pricing.pro": "Fino a 10 agenti AI",
    "gov.pricing.business": "Fino a 50 agenti AI",
    "gov.pricing.enterprise": "Agenti illimitati + SLA dedicato",
    "gov.pricing.start": "Inizia ora",
    "gov.docs.toast": "Documentazione in arrivo!",

    // About
    "about.hero.title1": "Costruiamo software",
    "about.hero.title2": "che dura.",
    "about.hero.desc": "ANTHERA nasce dall'esperienza sul campo: anni di lavoro su infrastrutture cloud enterprise, CMDB, ServiceNow e sviluppo SaaS. Sappiamo cosa funziona. E cosa no.",
    "about.mission.title": "La nostra",
    "about.mission.title2": "missione",
    "about.mission.text": "Creare prodotti software semplici da usare, robusti nell'architettura e compliant per design — pensati per le aziende europee che non vogliono scendere a compromessi tra innovazione e controllo.",
    "about.values.title": "I nostri valori",
    "about.v1.title": "Sovranità",
    "about.v1.desc": "Software europeo, per aziende europee. Nessuna dipendenza da infrastrutture fuori dal nostro controllo.",
    "about.v2.title": "Qualità ingegneristica",
    "about.v2.desc": "Ogni prodotto esce con test automatici, documentazione tecnica e architettura scalabile.",
    "about.v3.title": "Trasparenza",
    "about.v3.desc": "Nessuna feature nascosta, nessun lock-in. Saprai sempre cosa sta girando e perché.",
    "about.v4.title": "Accessibilità",
    "about.v4.desc": "Interfacce pensate per chi lavora, non per chi fa demo al board.",
    "about.team.title": "Chi siamo",
    "about.team.role": "Founder & Lead Engineer",

    // Contact
    "contact.hero.title": "Parliamoci.",
    "contact.hero.desc": "Hai domande su un prodotto, vuoi una demo o vuoi semplicemente capire se ANTHERA fa per te? Scrivici.",
    "contact.form.name": "Nome e Cognome",
    "contact.form.name.ph": "Mario Rossi",
    "contact.form.email": "Email aziendale",
    "contact.form.email.ph": "mario@azienda.it",
    "contact.form.company": "Azienda",
    "contact.form.company.ph": "Nome azienda",
    "contact.form.interest": "Mi interessa",
    "contact.form.interest.ph": "Seleziona...",
    "contact.form.interest.both": "Entrambi",
    "contact.form.interest.other": "Altro",
    "contact.form.message": "Messaggio",
    "contact.form.message.ph": "Raccontaci di cosa hai bisogno...",
    "contact.form.submit": "Invia messaggio",
    "contact.form.success.title": "Messaggio inviato!",
    "contact.form.success.desc": "Ti risponderemo entro 24 ore lavorative.",
    "contact.form.success.again": "Invia un altro messaggio",
    "contact.form.error": "Compila tutti i campi obbligatori.",
    "contact.form.toast": "Messaggio inviato con successo! Ti risponderemo entro 24h.",
    "contact.info.email": "Email",
    "contact.info.location": "Location",
    "contact.info.location.val": "Italia 🇮🇹",
    "contact.info.response": "Risposta",
    "contact.info.response.val": "Entro 24h lavorative",
    "contact.info.direct": "Preferisci scriverci direttamente? Invia un'email a",
    "contact.info.direct2": "e ti risponderemo il prima possibile.",

    // Footer
    "footer.desc": "Software che lavora per te.",
    "footer.desc2": "Non il contrario.",
    "footer.built": "Built in Italy. Designed for Europe.",
    "footer.products": "Prodotti",
    "footer.company": "Company",
    "footer.about": "Chi siamo",
    "footer.contact": "Contatti",
    "footer.legal": "Legal",
  },
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.products": "Products",
    "nav.cta": "Request Demo",

    // Home — Hero
    "home.hero.title1": "Software that works for you.",
    "home.hero.title2": "Not the other way around.",
    "home.hero.desc": "ANTHERA builds modern SaaS for companies and teams that want to automate, govern and grow — without depending on American tools.",
    "home.hero.cta1": "Discover PowerLeave",
    "home.hero.cta2": "Discover GOVERN.AI",
    "home.hero.badge1": "Made in Italy",
    "home.hero.badge2": "EU AI Act Ready",
    "home.hero.badge3": "GDPR Native",

    // Home — Why ANTHERA
    "home.why.title": "Why choose",
    "home.why.desc": "We build software with engineering rigor and native compliance for the European market.",
    "home.why.card1.title": "Digital Sovereignty",
    "home.why.card1.desc": "Our products are born in Europe, for European companies. Zero dependencies on US infrastructure.",
    "home.why.card2.title": "Modern Stack",
    "home.why.card2.desc": "React, FastAPI, MongoDB. Scalable architectures built to grow with your business.",
    "home.why.card3.title": "Native Compliance",
    "home.why.card3.desc": "GDPR, EU AI Act, DORA, NIS2. Compliance is not an add-on, it's in the product's DNA.",
    "home.why.card4.title": "For Real Teams",
    "home.why.card4.desc": "Interfaces designed for people who actually work. Not for those who run demos.",

    // Home — Products
    "home.products.title": "Our products",
    "home.products.desc": "Two SaaS platforms designed to solve real problems for European companies.",
    "home.products.pl.tag": "HR & TEAM MANAGEMENT",
    "home.products.pl.name": "ANTHERA PowerLeave",
    "home.products.pl.desc": "Leave and absence management for modern teams. Multi-tenant, analytics dashboard, integrated calendar and automatic company closures.",
    "home.products.pl.cta": "Discover PowerLeave",
    "home.products.gov.tag": "AI GOVERNANCE",
    "home.products.gov.name": "ANTHERA GOVERN.AI",
    "home.products.gov.desc": "The Sovereign Control Plane for enterprise AI agent governance. Audit trail, policy engine and EU compliance in a single platform.",
    "home.products.gov.cta": "Discover GOVERN.AI",

    // Home — Stats
    "home.stats.title": "Built with",
    "home.stats.title2": "engineering rigor",
    "home.stats.stat1": "Automated backend tests on PowerLeave",
    "home.stats.stat2": "API tests passed on GOVERN.AI",
    "home.stats.stat3": "EU standards supported",

    // Home — CTA
    "home.cta.title1": "Ready to take your processes to the",
    "home.cta.title2": "next level",
    "home.cta.desc": "Talk to us. No commitment, no pointless demos.",
    "home.cta.button": "Contact us",

    // PowerLeave
    "pl.badge": "Workforce Intelligence",
    "pl.hero.title1": "Manage your team's leave",
    "pl.hero.title2": "the simple, fast way.",
    "pl.hero.title3": "",
    "pl.hero.desc": "PowerLeave automates leave, absence and time-off management for your company. Intuitive dashboard, one-click approvals, advanced analytics and company closures with override system.",
    "pl.hero.cta1": "Start Free",
    "pl.hero.cta2": "Live Demo",
    "pl.hero.demo": "Demo",
    "pl.hero.democreds": "admin@demo.it / demo123",
    "pl.features.title": "Everything",
    "pl.features.title2": "you need",
    "pl.f1.title": "Smart Dashboard",
    "pl.f1.desc": "Complete overview of team absences with real-time statistics.",
    "pl.f2.title": "Quick Approvals",
    "pl.f2.desc": "Approve or reject requests with one click. Instant team notifications.",
    "pl.f3.title": "Shared Calendar",
    "pl.f3.desc": "View leave and time off for the whole team in a single unified calendar.",
    "pl.f4.title": "Advanced Analytics",
    "pl.f4.desc": "Detailed reports on leave usage, trends and absence distribution.",
    "pl.f5.title": "Company Closures",
    "pl.f5.desc": "Manage mandatory closures with a configurable override system.",
    "pl.f6.title": "Multi-Tenant",
    "pl.f6.desc": "Each company gets its own isolated, configurable space with JWT + Google auth.",
    "pl.stack.title": "Modern stack, SMB-ready",
    "pl.pricing.title": "Simple pricing",
    "pl.pricing.desc": "Start free, scale as you grow.",
    "pl.pricing.free.name": "Free",
    "pl.pricing.free.desc": "For small teams getting started",
    "pl.pricing.free.price": "€0",
    "pl.pricing.free.unit": "/month / user",
    "pl.pricing.free.f1": "Up to 5 employees",
    "pl.pricing.free.f2": "Basic dashboard",
    "pl.pricing.free.f3": "Shared calendar",
    "pl.pricing.free.cta": "Start free",
    "pl.pricing.pro.name": "Pro",
    "pl.pricing.pro.desc": "For growing SMBs",
    "pl.pricing.pro.price": "€4.99",
    "pl.pricing.pro.unit": "/month / user",
    "pl.pricing.pro.f1": "Up to 50 employees",
    "pl.pricing.pro.f2": "Advanced analytics",
    "pl.pricing.pro.f3": "Company closures",
    "pl.pricing.pro.f4": "Announcements board",
    "pl.pricing.pro.cta": "Get started",
    "pl.pricing.ent.name": "Enterprise",
    "pl.pricing.ent.desc": "Large teams and multinationals",
    "pl.pricing.ent.price": "Custom",
    "pl.pricing.ent.unit": "",
    "pl.pricing.ent.f1": "Unlimited employees",
    "pl.pricing.ent.f2": "SSO / SAML",
    "pl.pricing.ent.f3": "API Access",
    "pl.pricing.ent.f4": "Dedicated support",
    "pl.pricing.ent.cta": "Contact us",
    "pl.pricing.popular": "POPULAR",

    // GOVERN.AI
    "gov.hero.title1": "Govern your AI agents.",
    "gov.hero.title2": "Before someone else does.",
    "gov.hero.desc": "The Sovereign Control Plane for enterprise AI agent governance. Policy engine, complete audit trail and native EU standards compliance in a single platform.",
    "gov.hero.cta1": "Request Demo",
    "gov.hero.cta2": "Read Documentation",
    "gov.features.title1": "Your",
    "gov.features.title2": "control plane",
    "gov.features.title3": "for AI",
    "gov.f1.title": "Agent Registry",
    "gov.f1.desc": "Catalog and classify all enterprise AI agents with risk level.",
    "gov.f2.title": "Policy Engine",
    "gov.f2.desc": "Define and enforce granular policies: restriction, approval, rate_limit, logging, retention.",
    "gov.f3.title": "Complete Audit Trail",
    "gov.f3.desc": "Immutable log of all agent actions. No more black boxes.",
    "gov.f4.title": "Compliance Dashboard",
    "gov.f4.desc": "Real-time monitoring of compliance with 6 EU standards.",
    "gov.f5.title": "AI Compliance Assistant",
    "gov.f5.desc": "Chatbot expert in European regulations. Questions in Italian or English.",
    "gov.f6.title": "Bilingual IT/EN",
    "gov.f6.desc": "Native interface and assistant in Italian and English. Designed for EU companies.",
    "gov.standards.title1": "6 EU standards.",
    "gov.standards.title2": "Native.",
    "gov.std1.name": "EU AI Act",
    "gov.std1.desc": "European regulation on artificial intelligence",
    "gov.std2.name": "GDPR",
    "gov.std2.desc": "Personal data protection",
    "gov.std3.name": "ISO 27001",
    "gov.std3.desc": "Information security",
    "gov.std4.name": "ISO 42001",
    "gov.std4.desc": "Artificial intelligence management",
    "gov.std5.name": "DORA",
    "gov.std5.desc": "Digital operational resilience",
    "gov.std6.name": "NIS2",
    "gov.std6.desc": "Network and system security",
    "gov.stack.title": "Tech Stack",
    "gov.pricing.title": "Plans & Pricing",
    "gov.pricing.desc": "Choose the plan that fits your organization.",
    "gov.pricing.pro": "Up to 10 AI agents",
    "gov.pricing.business": "Up to 50 AI agents",
    "gov.pricing.enterprise": "Unlimited agents + dedicated SLA",
    "gov.pricing.start": "Get started",
    "gov.docs.toast": "Documentation coming soon!",

    // About
    "about.hero.title1": "We build software",
    "about.hero.title2": "that lasts.",
    "about.hero.desc": "ANTHERA was born from field experience: years of work on enterprise cloud infrastructure, CMDB, ServiceNow and SaaS development. We know what works. And what doesn't.",
    "about.mission.title": "Our",
    "about.mission.title2": "mission",
    "about.mission.text": "Creating software products that are simple to use, robust in architecture and compliant by design — built for European companies that refuse to compromise between innovation and control.",
    "about.values.title": "Our values",
    "about.v1.title": "Sovereignty",
    "about.v1.desc": "European software, for European companies. No dependencies on infrastructure outside our control.",
    "about.v2.title": "Engineering Quality",
    "about.v2.desc": "Every product ships with automated tests, technical documentation and scalable architecture.",
    "about.v3.title": "Transparency",
    "about.v3.desc": "No hidden features, no lock-in. You'll always know what's running and why.",
    "about.v4.title": "Accessibility",
    "about.v4.desc": "Interfaces designed for people who work, not for board demos.",
    "about.team.title": "Who we are",
    "about.team.role": "Founder & Lead Engineer",

    // Contact
    "contact.hero.title": "Let's talk.",
    "contact.hero.desc": "Have questions about a product, want a demo, or just want to understand if ANTHERA is right for you? Write to us.",
    "contact.form.name": "Full Name",
    "contact.form.name.ph": "John Smith",
    "contact.form.email": "Business Email",
    "contact.form.email.ph": "john@company.com",
    "contact.form.company": "Company",
    "contact.form.company.ph": "Company name",
    "contact.form.interest": "I'm interested in",
    "contact.form.interest.ph": "Select...",
    "contact.form.interest.both": "Both",
    "contact.form.interest.other": "Other",
    "contact.form.message": "Message",
    "contact.form.message.ph": "Tell us what you need...",
    "contact.form.submit": "Send message",
    "contact.form.success.title": "Message sent!",
    "contact.form.success.desc": "We'll get back to you within 24 business hours.",
    "contact.form.success.again": "Send another message",
    "contact.form.error": "Please fill in all required fields.",
    "contact.form.toast": "Message sent successfully! We'll reply within 24h.",
    "contact.info.email": "Email",
    "contact.info.location": "Location",
    "contact.info.location.val": "Italy 🇮🇹",
    "contact.info.response": "Response",
    "contact.info.response.val": "Within 24 business hours",
    "contact.info.direct": "Prefer to write directly? Send an email to",
    "contact.info.direct2": "and we'll get back to you as soon as possible.",

    // Footer
    "footer.desc": "Software that works for you.",
    "footer.desc2": "Not the other way around.",
    "footer.built": "Built in Italy. Designed for Europe.",
    "footer.products": "Products",
    "footer.company": "Company",
    "footer.about": "About us",
    "footer.contact": "Contact",
    "footer.legal": "Legal",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("it");

  const t = (key: string): string => {
    const dict = translations[lang];
    return Object.prototype.hasOwnProperty.call(dict, key) ? dict[key] : key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
